# Generated by Django 3.2.2 on 2022-03-20 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SampleSensorData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temperature', models.DecimalField(decimal_places=2, max_digits=5)),
                ('relative_humidity', models.DecimalField(decimal_places=2, max_digits=5)),
                ('pressure', models.DecimalField(decimal_places=2, max_digits=6)),
                ('wind_speed', models.DecimalField(decimal_places=2, max_digits=4)),
                ('short_wave_irradiation', models.DecimalField(decimal_places=4, max_digits=7)),
                ('soil_moisture', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
    ]
